### ISSUE TITLE
Simplify sbt configuration example in readme

### ISSUE THREAD

**Issue by ldeluigi** [nicolasfara/sbt-conventional-commits#117]
Based on:
https://github.com/sbt/sbt/issues/1224#issuecomment-331840364

the readme could show a simplified example for configuration:
```sbt
Global / onLoad ~= (_ andThen ("conventionalCommits" :: _))
```

**Comment by nicolasfara** [comment]
Sorry for the delay :)

Added your suggestion to the README.
